### PR TITLE
APPS-341 & APPS-184 novaseq and duplicate files fix

### PR DESCRIPTION
**Pull request by mhrvol**
Tested locally with python2 (python2 monitor_runs.py -c <.yml file> -p <test-project> -d .)

Assumed novaseq completion file name is "CopyComplete.txt"

Note that the whole pipeline was not started/tested and no real novaseq data were available for testing.

### CODE REVIEW

**Review by commandlinegirl — APPROVED** [review]
LGTM.

**Comment by davisfeng70** [comment]
Please add a CopyComplete check in monitor_runs.py as well.  See line 204.

If it is NovaSeq, then it is complete when CopyComplete is there, otherwise, it is complete when the other 2 files are there.

**Review by commandlinegirl — APPROVED** [review]
LGTM

**Comment by mhrvol** [comment]
> Please add a CopyComplete check in monitor_runs.py as well. See line 204.
> 
> If it is NovaSeq, then it is complete when CopyComplete is there, otherwise, it is complete when the other 2 files are there.

@davisfeng70  is it ok now? I cannot re-request review on github, so I decided to do it this way

**Comment by davisfeng70** [comment]
LGTM

**Pull request merged**
