### PR TITLE
update YAML escape for newer Ansible

### PR DESCRIPTION
**Pull request by tomkinsc**
This updates a few more YAML values for the `lineinfile` tasks to use correct YAML escaping of quotes, including for the`downstream_inputs` parameter, which is or can be a JSON object and must be escaped carefully (broken out into separate YAML keys here to avoid risky nesting of quotes).

### CODE REVIEW

**Comment by mlin** [comment]
@tomkinsc any ideas on https://travis-ci.org/dnanexus-rnd/dx-streaming-upload/builds/414948330 ?

**Comment by tomkinsc** [comment]
Is that a token issue because it is from my branch?

**Comment by mlin** [comment]
I pulled and pushed your branch, so I doubt it. It could be something to do with the escaping, check this weird message out carefully:

```
fatal: [localhost]: FAILED! => {"failed": true, "msg": "file or module does not exist: /home/travis/build/dnanexus-rnd/dx-streaming-upload/tests/https:/wiki.dnanexus.com/images/files/dx-toolkit-current-ubuntu-14.04-amd64.tar.gz"}
```

**Comment by tomkinsc** [comment]
How about now, @mlin?

**Comment by mlin** [comment]
@tomkinsc sorry for the cumbersome iteration here but https://travis-ci.org/dnanexus-rnd/dx-streaming-upload/builds/416628814

**Comment by tomkinsc** [comment]
Strange that the syntax check passes yet the execution fails because of a syntax error. I rolled back the changes to the failing task. How about now?

**Comment by mlin** [comment]
Looks good, thanks, sorry for the slow iteration! https://travis-ci.org/dnanexus-rnd/dx-streaming-upload/builds/418065194

**Pull request merged**
